### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startPayment on channel flutter_razorpay_sdk)

### ISSUE THREAD

**Issue by gyanverma** [gibbsvjy007/flutter_razorpay_sdk#7]
Any idea

`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startPayment on channel flutter_razorpay_sdk)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      FlutterRazorpaySdk.openPaymentDialog (package:flutter_razorpay_sdk/flutter_razorpay_sdk.dart:23:30)
#3      _ItemDetailScreenState._showNativeView (package:projectName/ui/item_detail.dart:130:48)
#4      _ItemDetailScreenState.build.<anonymous closure> (package:projectName/ui/item_detail.dart:35:14)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer.handleTapUp (pac<…>
`

**Comment by gyanverma** [comment]
Solved by upgrading the ios build version to 10.0
